MODEL:
  STRUCTURE:
    STEM_CHANNELS: [ 64 ]
    STAGE1:
      MODULE_NUM: 1
      BRANCH_NUM: 1
      BLOCK: BASIC
      BLOCK_NUM: [ 4 ]
      NUM_CHANNELS: [ 64 ]

    STAGE2:
      MODULE_NUM: 1
      BRANCH_NUM: 2
      BLOCK: BASIC
      BLOCK_NUM: [ 4,4 ]
      NUM_CHANNELS: [ 32,64 ]
    STAGE3:
      MODULE_NUM: 4
      BRANCH_NUM: 3
      BLOCK: BASIC
      BLOCK_NUM: [ 4,4,4 ]
      NUM_CHANNELS: [ 32,64,128 ]
    STAGE4:
      MODULE_NUM: 3
      BRANCH_NUM: 4
      BLOCK: BASIC
      BLOCK_NUM: [ 4,4,4,4 ]
      NUM_CHANNELS: [ 32,64,128,256 ]
    CAT:
      BLOCK: BASIC
      NUM_CHANNELS: 32
    SEG_HEAD:
      BLOCK: BASIC
      CLASS_NUM: 2
    KPT_HEAD:
      BLOCK: BASIC
      KPT_NUM: 6

  INIT_WEIGHTS: True
  PRETRAINED: ''